version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    restart: always
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    depends_on:
      - kong-database
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong

  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-database
      - kong-migrations
    restart: always
    environment:
      KONT_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_LICENSE_DATA:
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"

  mongo:
    image: mongo:7.0
    ports:
      - "27020:27017"
    volumes:
      - ./db-data/mongo/:/data/db
      
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis/:/data