spring:
  application:
    name: category-service
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60


server:
  port: 9130


# ENVIRONMENT
JWT_SECRET: vVarX3ETLuR35pAe8LLVSEieaIxvBrz6X2B0eiN1HY4cdf3jYwBUKISJhDDXD60gsZiL9HLTYPoVwrSGa628XGmjJkGF04J3f4On
JWT_EXPIRATION: 60


REDIS_HOST: localhost
# REDIS_HOST=redis
REDIS_PORT: 6380