spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:users}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 60

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      "[spring.json.type.mapping]": com.phuc.reviewservice.events.message.AvgRatingEvent:com.phuc.productservice.events.message.AvgRatingEvent





server:
  port: 9140

# ENVIRONMENT
JWT_SECRET: vVarX3ETLuR35pAe8LLVSEieaIxvBrz6X2B0eiN1HY4cdf3jYwBUKISJhDDXD60gsZiL9HLTYPoVwrSGa628XGmjJkGF04J3f4On
JWT_EXPIRATION: 60



CLOUD_NAME: dp4tp9gwa
CLOUD_KEY: 774542943245931
CLOUD_SECRET: mbwq5AMRewXo8Fo8ENBXrJRbjFE
