server:
  port: 9170
  mode: "dev"
postgres:
  dbName: users
  username: postgres
  password: password
  host: postgresql
  port: 5432
  sslmode: disable
redis:
  host: redis
  port: 6379
kafka:
  brokers: kafka:29092
  topic: place-order-events-topics
jwt:
  secret: vVarX3ETLuR35pAe8LLVSEieaIxvBrz6X2B0eiN1HY4cdf3jYwBUKISJhDDXD60gsZiL9HLTYPoVwrSGa628XGmjJkGF04J3f4On
  expire: 60
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
