server:
  port: 9170
  mode: "dev"
postgres:
  dbName: users
  username: postgres
  password: password
  host: localhost
  port: 5432
  sslmode: disable
redis:
  port: 6379
  host: localhost
kafka:
  brokers: localhost:9092
  topic: place-order-events-topics
security:
  jwt:
    key: vVarX3ETLuR35pAe8LLVSEieaIxvBrz6X2B0eiN1HY4cdf3jYwBUKISJhDDXD60gsZiL9HLTYPoVwrSGa628XGmjJkGF04J3f4On
    expiration: 60
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true